### PR TITLE
Fix starred file under encrypted repo still accessible bug

### LINKED ISSUE #552: Starred files from encrypted library are accessible even if encrypted library isn't
App Version: 2.0.6
Os CyanogenMod: 12.1-20151007 android: 5.1.1

Situation:
When using KeePass2Android with seadroid I cannot access files from encrypted library (grayed out with lock icon) even when I have just inserted password. (Still I can open one file from seadroid and select KeePass2Andriod as application to use.)

Problem: 
Even If I can't access encrypted library I can open starred from encrypted library in "Starred" tab. 

Logic: 
If I'm unable to access encrypted library, then I should not be able to access files from encrypted library wherever they are starred or not.

### PR DESCRIPTION
**Pull request by Logan676**
Fix #552

### CODE REVIEW

File: app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java [hunk 1]
```diff
@@ -525,25 +527,25 @@ public void onTaskSuccess() {
...
         } else {
-            if (!dataManager.getRepoEnckeySet(repo.id)) {
-                Pair<String, String> pair = dataManager.getRepoEncKey(repo.id);
-                showPasswordDialog(repo.name, repo.id, taskDialogListener, pair == null ? null : pair.first);
+            if (!getDataManager().getRepoEnckeySet(repo.id)) {
+                Pair<String, String> pair = getDataManager().getRepoEncKey(repo.id);
+                showEncDialog(repo.name, repo.id,repo.magic, repo.encKey, repo.encVersion, taskDialogListener, pair == null ? null : pair.first);
+                return false;
             } else {
-                taskDialogListener.onTaskSuccess();
```
Comment (Logan676) [inline app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java]: If set `taskDialogListener.onTaskSuccess();` here will lead up to an infinite loop which caused stack overflow error. This bug was introduced since tag [2.0.0](https://github.com/haiwen/seadroid/blob/2.1.0/app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java#L500). The fix is removing the line of code.

The modifications have passed the following test cases.

1. Open a starred file
  - With local decrypt disable, password required or password saved
  - With local decrypt enable, password required or password saved
2. Open a repo file
  - With local decrypt disable, password required or password saved
  - With local decrypt enable, password required or password saved
3. Edit a repo file via overflow menu
  - With local decrypt disable, password required or password saved
  - With local decrypt enable, password required or password saved
4. Sort file via overflow menu
  - With local decrypt disable, password required or password saved
  - With local decrypt enable, password required or password saved
